[1]
Component = "Echidna2.ReferenceFieldEditor, Echidna2"
Rect = "2"
Text = "3"
Button = "4"

[2]
Prefab = "../Prefabs/FullRectWithHierarchy.toml"
HorizontalExpand = true
Margin = 4.0
Children = [ "3" ]

[3]
Prefab = "../Prefabs/TextRect.toml"
Justification = "Left"
LocalScale = { X = 0.5, Y = 0.5 }

[4]
Component = "Echidna2.Gui.Button, Echidna2.Gui"
RectTransform = "2"