[1]
Component = "Echidna2.Vector3FieldEditor, Echidna2"
Layout = "2"
XFieldEditor = "3"
YFieldEditor = "4"
ZFieldEditor = "5"

[2]
Prefab = "../Prefabs/HLayoutWithHierarchy.toml"
Name = "Vector3 Layout"
Spacing = 0.1
Children = [ "3", "4", "5" ]

[3]
Prefab = "DoubleFieldEditor.toml"

[4]
Prefab = "DoubleFieldEditor.toml"

[5]
Prefab = "DoubleFieldEditor.toml"
