[1]
Component = "Echidna2.Vector2FieldEditor, Echidna2"
Layout = "2"
XFieldEditor = "3"
YFieldEditor = "4"

[2]
Prefab = "../Prefabs/HLayoutWithHierarchy.toml"
Name = "Vector2 Layout"
Spacing = 0.1
Children = [ "3", "4" ]

[3]
Prefab = "DoubleFieldEditor.toml"

[4]
Prefab = "DoubleFieldEditor.toml"
