[This]
Component = "Echidna2.Prefabs.Gui.ButtonText, Echidna2.Gui"
[This.Values]
TextRect = "2"
Button = "3"

[2]
Prefab = "Prefabs.Gui.TextRect"

[3]
Component = "Echidna2.Gui.Button, Echidna2.Gui"
[3.Values]
RectTransform = "2"