Using = [
    "Echidna2.Prefabs.Gui",
    "Echidna2.Gui",
]

[This]
Interfaces = [
    "ICanBeLaidOut",
]

[[This.Properties]]
PropertyType = "Component"
Type = "ButtonRect"
Name = "ButtonRect"

[[This.Properties]]
PropertyType = "Reference"
Type = "TextRect"
Name = "TextRect"

[[This.Properties]]
PropertyType = "Value"
Type = "string"
Name = "TextString"
GetterContent = "return TextRect.TextString;"
SetterContent = "TextRect.TextString = value;"

[This.Values]
ButtonRect = "0"
TextRect = "1"

[0]
Prefab = "Prefabs.Gui.ButtonRect"

[0.Values]
Name = "Button Rect With Text"
Margin = 5.0
Children = [ "1" ]

[1]
Prefab = "Prefabs.Gui.TextRect"

[1.Values]
LocalScale = { X = 0.5, Y = 0.5 }