[1]
Component = "Echidna2.Prefabs.Gui.FullRectWithHierarchy, Echidna2.Gui"
Named = "2"
RectTransform = "4"
Layout = "5"
Rect = "6"
PrefabChildren = "3"
Visibility = "7"

[2]
Component = "Echidna2.Core.Named, Echidna2.Core"
Name = "Full Rect With Hierarchy"

[3]
Component = "Echidna2.Core.Hierarchy, Echidna2.Core"

[4]
Component = "Echidna2.Gui.RectTransform, Echidna2.Gui"

[5]
Component = "Echidna2.Gui.FullLayout, Echidna2.Gui"
RectTransform = "4"
Hierarchy = "3"

[6]
Component = "Echidna2.Gui.Rect, Echidna2.Gui"
RectTransform = "4"

[7]
Component = "Echidna2.Rendering.Visibility, Echidna2.Rendering"
NotificationPropagator = "3"
