[This]
Component = "Echidna2.Prefabs.Gui.RectLayoutWithHierarchy, Echidna2.Gui"
[This.Values]
Named = "2"
RectTransform = "4"
Layout = "5"
PrefabChildren = "3"

[2]
Component = "Echidna2.Core.Named, Echidna2.Core"
[2.Values]
Name = "Rect Layout With Hierarchy"

[3]
Component = "Echidna2.Core.Hierarchy, Echidna2.Core"

[4]
Component = "Echidna2.Gui.RectTransform, Echidna2.Gui"

[5]
Component = "Echidna2.Gui.RectLayout, Echidna2.Gui"
[5.Values]
RectTransform = "4"
Hierarchy = "3"
