Using = ["Echidna2.Gui", "Echidna2.Prefabs.Gui", "Echidna2.Rendering"]

[This]
Interfaces = [
    "ICanBeLaidOut",
]

[[This.Properties]]
PropertyType = "Component"
Type = "Named"
Name = "Named"

[[This.Properties]]
PropertyType = "Component"
Type = "RectTransform"
Name = "RectTransform"

[[This.Properties]]
PropertyType = "Component"
Type = "FullLayout"
Name = "Layout"

[[This.Properties]]
PropertyType = "Component"
Type = "Hierarchy"
Name = "LayoutChildren"

[[This.Properties]]
PropertyType = "Reference"
Type = "FullLayoutWithHierarchy"
Name = "PrefabChildren"

[[This.Properties]]
PropertyType = "Reference"
Type = "RectLayoutWithHierarchy"
Name = "PrefabChildrenContainer"

[[This.Properties]]
PropertyType = "Reference"
PropertySerializer = "ChildrenSerializer"
Type = "IEnumerable<object>"
Name = "Content"
SetterContent = "PrefabChildren.Children = value;"
GetterContent = "return PrefabChildren.Children;"

[[This.Properties]]
PropertyType = "Reference"
Type = "Slider"
Name = "Slider"

[[This.Events]]
EventType = "Notification"
Name = "Update"
Content = """
double possibleMovement = (PrefabChildren.LocalSize.Y - PrefabChildrenContainer.LocalSize.Y).Clamped(0, float.MaxValue);
PrefabChildren.LocalPosition = new Vector2(0, -Slider.Value.Map(0, 1, -1, 1) * possibleMovement / 2);
PrefabChildren.LocalSize = new Vector2(PrefabChildrenContainer.LocalSize.X, PrefabChildren.MinimumSize.Y);
"""

[[This.Events]]
EventType = "Notification"
Name = "MouseWheelScrolled"
Content = """
if (RectTransform.ContainsGlobalPoint(notification.GlobalPosition.XY))
    Slider.Value += notification.Offset.Y * 100 / PrefabChildren.LocalSize.Y;
"""

[This.Values]
Named = "02"
RectTransform = "04"
Layout = "05"
LayoutChildren = "03"
PrefabChildren = "2"
PrefabChildrenContainer = "6"
Slider = "3"

[02]
Component = "Echidna2.Core.Named, Echidna2.Core"

[02.Values]
Name = "Scroll Area"

[03]
Component = "Echidna2.Core.Hierarchy, Echidna2.Core"

[03.Values]
Children = [ "1" ]

[04]
Component = "Echidna2.Gui.RectTransform, Echidna2.Gui"

[05]
Component = "Echidna2.Gui.FullLayout, Echidna2.Gui"

[05.Values]
RectTransform = "04"
Hierarchy = "03"

[1]
Prefab = "Prefabs.Gui.HLayoutWithHierarchy"

[1.Values]
Children = [ "5", "3" ]

[2]
Prefab = "Prefabs.Gui.FullLayoutWithHierarchy"

[2.Values]
Name = "Area"

[3]
Prefab = "Prefabs.Gui.Slider"

[3.Values]
VerticalExpand = true
Value = 1

[5]
Prefab = "Prefabs.Gui.FullRectWithHierarchy"

[5.Values]
HorizontalExpand = true
Margin = 5
Children = [ "6" ]

[6]
Prefab = "Prefabs.Gui.RectLayoutWithHierarchy"

[6.Values]
LayOutChildren = false
ClipChildren = true
Children = [ "2" ]