[This]
Component = "Echidna2.Prefabs.Editor.AddComponentWindow, Echidna2"
[This.Values]
Window = "1"
ComponentList = "11"

[1]
Prefab = "../Gui/FullRectWindow.toml"
[1.Values]
Margin = 10.0
LocalSize = { X = 300, Y = 400 }
Depth = 15
Children = [ "4" ]

[2]
Prefab = "../Gui/ButtonRect.toml"
Properties = [
    { PropertyType = "Reference", Type = "Echidna2.Prefabs.Editor.AddComponentWindow", Name = "AddComponentWindow" },
    { PropertyType = "Reference", Type = "Echidna2.Prefabs.Gui.FullRectWindow", Name = "Window" },
]
Events = [
    { EventType = "Self", Target = "Button", Name = "Clicked", Args = [], Content = """
Window.CloseWindow();
AddComponentWindow.AddNewComponent();
""" },
]
[2.Values]
Margin = 5.0
Children = [ "3" ]
AddComponentWindow = "This"
Window = "1"

[3]
Prefab = "../Gui/TextRect.toml"
TextString = "Add New Component"
LocalScale = { X = 0.5, Y = 0.5 }

[4]
Prefab = "../Gui/VLayoutWithHierarchy.toml"
Children = [ "10", "2", "5" ]

[5]
Prefab = "../Gui/HLayoutWithHierarchy.toml"
Children  = [ "6", "8" ]

[6]
Prefab = "../Gui/ButtonRect.toml"
Properties = [
    { PropertyType = "Reference", Type = "Echidna2.Prefabs.Gui.FullRectWindow", Name = "Window" },
]
Events = [
    { EventType = "Self", Target = "Button", Name = "Clicked", Args = [], Content = """
Window.CloseWindow();
""" },
]
[6.Values]
HorizontalExpand = true
Margin = 5.0
Children = [ "7" ]
Window = "1"

[7]
Prefab = "../Gui/TextRect.toml"
TextString = "Cancel"
LocalScale = { X = 0.5, Y = 0.5 }

[8]
Prefab = "../Gui/ButtonRect.toml"
Properties = [
    { PropertyType = "Reference", Type = "Echidna2.Prefabs.Editor.AddComponentWindow", Name = "AddComponentWindow" },
    { PropertyType = "Reference", Type = "Echidna2.Prefabs.Gui.FullRectWindow", Name = "Window" },
]
Events = [
    { EventType = "Self", Target = "Button", Name = "Clicked", Args = [], Content = """
Window.CloseWindow();
AddComponentWindow.UseSelectedComponent();
""" },
]
[8.Values]
HorizontalExpand = true
Margin = 5.0
Children = [ "9" ]
AddComponentWindow = "0"
Window = "1"

[9]
Prefab = "../Gui/TextRect.toml"
TextString = "Confirm"
LocalScale = { X = 0.5, Y = 0.5 }

[10]
Prefab = "../Gui/FullRectWithHierarchy.toml"
VerticalExpand = true
Margin = 5.0
Children = [ "11" ]

[11]
Prefab = "../Gui/VLayoutWithHierarchy.toml"
Spacing = 5