[0]
Component = "Echidna2.Prefabs.Editor.AddComponentWindow, Echidna2"
Window = "1"
ComponentList = "11"

[1]
Prefab = "../Gui/FullRectWindow.toml"
Margin = 10.0
LocalSize = { X = 300, Y = 400 }
Depth = 15
Children = [ "4" ]

[2]
Prefab = "../Gui/ButtonRect.toml"
Children = [ "3" ]
ScriptContent = """
[SerializedReference] public Echidna2.Prefabs.Editor.AddComponentWindow AddComponentWindow = null!;
[SerializedReference] public Echidna2.Prefabs.Gui.FullRectWindow Window = null!;
"""
AddComponentWindow = "0"
Window = "1"
Clicked = """
Window.CloseWindow();
AddComponentWindow.AddNewComponent();
"""

[3]
Prefab = "../Gui/TextRect.toml"
TextString = "Add New Component"
LocalScale = { X = 0.5, Y = 0.5 }

[4]
Prefab = "../Gui/VLayoutWithHierarchy.toml"
Children = [ "10", "2", "5" ]

[5]
Prefab = "../Gui/HLayoutWithHierarchy.toml"
Children  = [ "6", "8" ]

[6]
Prefab = "../Gui/ButtonRect.toml"
HorizontalExpand = true
Children = [ "7" ]
ScriptContent = """
[SerializedReference] public Echidna2.Prefabs.Gui.FullRectWindow Window = null!;
"""
Window = "1"
Clicked = "Window.CloseWindow();"

[7]
Prefab = "../Gui/TextRect.toml"
TextString = "Cancel"
LocalScale = { X = 0.5, Y = 0.5 }

[8]
Prefab = "../Gui/ButtonRect.toml"
HorizontalExpand = true
Children = [ "9" ]
ScriptContent = """
[SerializedReference] public Echidna2.Prefabs.Gui.FullRectWindow Window = null!;
"""
Window = "1"
Clicked = """
Window.CloseWindow();
Console.WriteLine("Confirm!");
"""

[9]
Prefab = "../Gui/TextRect.toml"
TextString = "Confirm"
LocalScale = { X = 0.5, Y = 0.5 }

[10]
Prefab = "../Gui/FullRectWithHierarchy.toml"
VerticalExpand = true
Children = [ "11" ]

[11]
Prefab = "../Gui/VLayoutWithHierarchy.toml"
