Using = [
    "Notifications.Editor",
    "Echidna2.Prefabs.Gui",
    "Echidna2.Prefabs.Editor",
    "Echidna2.Rendering",
]

[[This.Properties]]
PropertyType = "Component"
Type = "ViewportGui"
Name = "Viewport"

[[This.Properties]]
PropertyType = "Component"
Type = "ViewportGuiControls"
Name = "Controls"

[[This.Events]]
EventType = "Reference"
Target = "Controls"
Name = "Moved"
Args = [{ Type = "Vector2", Name = "position" }]
Content = """
Camera.GlobalPosition = position;
"""

[[This.Events]]
EventType = "Reference"
Target = "Controls"
Name = "Zoomed"
Args = [{ Type = "double", Name = "zoom" }]
Content = """
Camera.Zoom = zoom;
"""

[This.Values]
Viewport = "2"
Controls = "3"

[2]
Prefab = "Prefabs.Editor.ViewportGui"
[2.Values]
Children = [ "4", "5" ]

[3]
Prefab = "Prefabs.Editor.ViewportGuiControls"
[3.Values]
RectTransform = "2"

[4]
Prefab = "Prefabs.Editor.CodeNode"
[4.Values]
AnchorOffsetPosition = { X = 0.0, Y = 0.0 }

[5]
Prefab = "Prefabs.Editor.CodeNode"
[5.Values]
AnchorOffsetPosition = { X = 300.0, Y = 300.0 }