[0]
Component = "Echidna2.Prefabs.Editor.ComponentPanel, Echidna2"
Name = "Component Panel"
Rect = "1"
PrefabNameText = "3"
ComponentNameText = "4"
Fields = "5"
Components = "7"

[1]
Prefab = "../Gui/FullRectWithHierarchy.toml"
Name = "Interior Rect"
Margin = 10.0
Children = [ "6" ]

[2]
Prefab = "../Gui/VLayoutWithHierarchy.toml"
Name = "Interior Layout"
HorizontalExpand = true
Children = [ "3", "4", "5" ]

[3]
Prefab = "../Gui/TextRect.toml"
Name = "Object Name"
LocalScale = { X = 0.5, Y = 0.5 }

[4]
Prefab = "../Gui/TextRect.toml"
Name = "Component Class"
LocalScale = { X = 0.5, Y = 0.5 }

[5]
Prefab = "../Gui/VLayoutWithHierarchy.toml"
Name = "Fields"

[6]
Prefab = "../Gui/HLayoutWithHierarchy.toml"
Name = "Horizontal Split"
Children = [ "2", "7" ]

[7]
Prefab = "../Gui/VLayoutWithHierarchy.toml"
Name = "Component List"