[0]
Component = "Echidna2.Prefabs.Editor.ComponentPanel, Echidna2"
Name = "Component Panel"
Rect = "1"
PrefabNameText = "3"
ComponentNameText = "4"
Fields = "5"

[1]
Prefab = "../Gui/FullRectWithHierarchy.toml"
Name = "Interior Rect"
Margin = 10.0
Children = [ "2" ]

[2]
Prefab = "../Gui/VLayoutWithHierarchy.toml"
Name = "Interior Layout"
Children = [ "3", "4", "5" ]

[3]
Prefab = "../Gui/TextRect.toml"
Namme = "Object Name"
LocalScale = { X = 0.5, Y = 0.5 }
MinimumSize = { X = 0.0, Y = 25.0 }

[4]
Prefab = "../Gui/TextRect.toml"
Namme = "Component Class"
LocalScale = { X = 0.5, Y = 0.5 }
MinimumSize = { X = 0.0, Y = 25.0 }

[5]
Prefab = "../Gui/VLayoutWithHierarchy.toml"
Name = "Fields"