[This]
Component = "Echidna2.Prefabs.Editor.EditorViewport3D, Echidna2"
[This.Values]
Viewport = "2"
CameraPivot = "3"

[2]
Prefab = "Prefabs.Editor.Viewport3D"

[3]
Component = "Echidna2.Rendering3D.Transform3D, Echidna2.Rendering3D"