Using = ["Notifications.Editor", "Echidna2.Gui", "Echidna2.Prefabs.Gui"]

[This]
Interfaces = ["ICanBeLaidOut"]
Properties = [
    { PropertyType = "Component", Type = "Named", Name = "Named" },
    { PropertyType = "Component", Type = "RectTransform", Name = "RectTransform" },
    { PropertyType = "Component", Type = "FullLayout", Name = "Layout" },
    { PropertyType = "Component", Type = "Hierarchy", Name = "DisplayElements", ExposeProperties = false },
    { PropertyType = "Public", Type = "PrefabRoot?", Name = "HierarchyToDisplay", SetterContent = """
DisplayElements.ClearChildren();
_HierarchyToDisplay = value;
if (HierarchyToDisplay is not null)
{
    FullLayoutWithHierarchy box = BoxOfHierarchy(HierarchyToDisplay, HierarchyToDisplay.RootPair);
    box.LeftMargin = 0;
    DisplayElements.AddChild(box);
}
""" },
    { PropertyType = "Event", Type = "ComponentPair", Name = "ItemSelected" },
]
Functions = [
    { FunctionType = "Private", ReturnType = "FullLayoutWithHierarchy", Name = "BoxOfHierarchy", Args = [{ Type = "PrefabRoot", Name = "root" }, { Type = "ComponentPair", Name = "component" }], Content = """
string name = INamed.GetName(component.Object);

FullLayoutWithHierarchy box = Project.Instantiate<FullLayoutWithHierarchy>("Prefabs.Gui.FullLayoutWithHierarchy");
box.Name = $"Box for {name}";
box.AnchorPreset = AnchorPreset.Full;
box.LeftMargin = 10;
VLayoutWithHierarchy layout = Project.Instantiate<VLayoutWithHierarchy>("Prefabs.Gui.VLayoutWithHierarchy");
layout.Name = $"Layout for box for {name}";
layout.AnchorPreset = AnchorPreset.Full;
box.AddChild(layout);

ButtonRect button = Project.Instantiate<ButtonRect>("Prefabs.Gui.ButtonRect");
button.AnchorPreset = AnchorPreset.Full;
button.Margin = 5;
button.MouseUp += _ => ItemSelected?.Invoke(component);
layout.AddChild(button);

TextRect text = Project.Instantiate<TextRect>("Prefabs.Gui.TextRect");
text.TextString = name;
if (component.Object is INamed named)
    named.NameChanged += name => text.TextString = name;
text.Justification = TextJustification.Left;
text.AnchorPreset = AnchorPreset.Full;
text.LocalScale = Vector2.One * 0.5;
button.AddChild(text);

if (component.Object is IHasChildren hasChildren)
    foreach (object child in hasChildren.Children.Where(root.Owns))
        layout.AddChild(BoxOfHierarchy(root, new ComponentPair(child, root[child])));

return box;
""" },
]

[This.Values]
Named = "2"
RectTransform = "4"
Layout = "5"
DisplayElements = "3"

[2]
Component = "Echidna2.Core.Named, Echidna2.Core"
[2.Values]
Name = "Hierarchy Display"

[3]
Component = "Echidna2.Core.Hierarchy, Echidna2.Core"

[4]
Component = "Echidna2.Gui.RectTransform, Echidna2.Gui"

[5]
Component = "Echidna2.Gui.FullLayout, Echidna2.Gui"
[5.Values]
RectTransform = "4"
Hierarchy = "3"