[This]
Component = "Echidna2.Prefabs.Editor.Viewport3D, Echidna2"
[This.Values]
Named = "2"
RectTransform = "3"
RenderTarget = "5"
Hierarchy = "6"
Camera = "7"

[2]
Component = "Echidna2.Core.Named, Echidna2.Core"
[2.Values]
Name = "Viewport"

[3]
Component = "Echidna2.Gui.RectTransform, Echidna2.Gui"

[5]
Component = "Echidna2.Rendering.RenderTarget, Echidna2.Rendering"
[5.Values]
CameraHaver = "7"

[6]
Component = "Echidna2.Core.Hierarchy, Echidna2.Core"

[7]
Component = "Echidna2.Rendering3D.Camera3D, Echidna2.Rendering3D"
[7.Values]
Size = { X = 800.0, Y = 600.0 }
World = "6"
Transform = "8"

[8]
Component = "Echidna2.Rendering3D.Transform3D, Echidna2.Rendering3D"