Using = ["Notifications.Editor", "Echidna2.Prefabs.Gui", "Echidna2.Gui"]

[This]
Interfaces = [
    "IFieldEditor",
]
Properties = [
    { PropertyType = "Component", Type = "FullRectWithHierarchy", Name = "Rect" },
    { PropertyType = "Component", Type = "Button", Name = "Button", ExposeProperties = false },
    { PropertyType = "Reference", Type = "TextRect", Name = "Text" },
    { PropertyType = "Public", Type = "object?", Name = "Value", SetterContent = """
_Value = value;
Text.TextString = INamed.GetName(value) ?? "null";
ValueChanged?.Invoke(value);
""" },
    { PropertyType = "Public", Type = "Type", Name = "ComponentType" },
    { PropertyType = "Private", Type = "Editor", Name = "Editor" },
    { PropertyType = "Event", Type = "object?", Name = "ValueChanged" },
]
Events = [
    { EventType = "Notification", Name = "EditorInitialize", Content = """
Editor = notification.Editor;
""" },
    { EventType = "Reference", Target = "Button", Name = "MouseDown", Args = [], Content = """
SelectReferenceWindow window = Project.Instantiate<SelectReferenceWindow>("Prefabs.Editor.SelectReferenceWindow");
window.ComponentType = ComponentType;
window.Field = this;
INotificationPropagator.Notify(new EditorInitialize_Notification(Editor), window);
Editor.QueueAddChild(window);
""" },
]
Functions = [
    { ReturnType = "void", Name = "Load", Args = [{ Type = "object?", Name = "value" }], Content = "Value = value;" },
]

[This.Values]
Rect = "2"
Text = "3"
Button = "4"

[2]
Prefab = "Prefabs.Gui.FullRectWithHierarchy"
[2.Values]
HorizontalExpand = true
Margin = 4.0
ClipChildren = true
Children = [ "3" ]

[3]
Prefab = "Prefabs.Gui.TextRect"
[3.Values]
Justification = "Left"
LocalScale = { X = 0.5, Y = 0.5 }

[4]
Component = "Echidna2.Gui.Button, Echidna2.Gui"
[4.Values]
RectTransform = "2"