[This]
Component = "Echidna2.Prefabs.Editor.FieldEditors.ReferenceFieldEditor, Echidna2"
[This.Values]
Rect = "2"
Text = "3"
Button = "4"

[2]
Prefab = "../../Gui/FullRectWithHierarchy.toml"
[2.Values]
HorizontalExpand = true
Margin = 4.0
ClipChildren = true
Children = [ "3" ]

[3]
Prefab = "../../Gui/TextRect.toml"
[3.Values]
Justification = "Left"
LocalScale = { X = 0.5, Y = 0.5 }

[4]
Component = "Echidna2.Gui.Button, Echidna2.Gui"
[4.Values]
RectTransform = "2"