[1]
Component = "Echidna2.Prefabs.Editor.FieldEditors.Vector3FieldEditor, Echidna2"
Layout = "2"
XFieldEditor = "3"
YFieldEditor = "4"
ZFieldEditor = "5"

[2]
Prefab = "../../Gui/HLayoutWithHierarchy.toml"
Name = "Vector3 Layout"
Spacing = 10
Children = [ "3", "4", "5" ]
HorizontalExpand = true

[3]
Prefab = "DoubleFieldEditor.toml"

[4]
Prefab = "DoubleFieldEditor.toml"

[5]
Prefab = "DoubleFieldEditor.toml"
