[0]
Component = "Echidna2.ComponentPanel, Echidna2"
Name = "Component Panel"
Rect = "1"
NameText = "3"
Fields = "4"

[1]
Prefab = "FullRectWithHierarchy.toml"
Margin = 10.0
Children = [ "2" ]

[2]
Prefab = "VLayoutWithHierarchy.toml"
Children = [ "3", "4" ]

[3]
Prefab = "TextRect.toml"
TextString = "No object selected"
LocalScale = { X = 0.5, Y = 0.5 }
MinimumSize = { X = 0.0, Y = 25.0 }

[4]
Prefab = "VLayoutWithHierarchy.toml"