[1]
Component = "Echidna2.Editor, Echidna2"
Named = "01"
RectTransform = "02"
RectLayout = "03"
PrefabChildren = "04"
Viewport = "2"
PrefabPath = "Prefabs/Some3dScene.toml"

[01]
Component = "Echidna2.Core.Named, Echidna2.Core"
Name = "Editor"

[02]
Component = "Echidna2.Gui.RectTransform, Echidna2.Gui"
IsGlobal = true
AnchorPreset = "Full"

[03]
Component = "Echidna2.Gui.RectLayout, Echidna2.Gui"
RectTransform = "02"
Hierarchy = "04"

[04]
Component = "Echidna2.Core.Hierarchy, Echidna2.Core"
Children = [ "2", "3" ]

[2]
Prefab = "EditorViewport3D.toml"
Name = "Scene"
AnchorPreset = "Full"

[3]
Prefab = "RectLayoutWithHierarchy.toml"
Name = "Overlay"
AnchorPreset = "Full"
Children = [ "4" ]

[4]
Prefab = "RectWithHierarchy.toml"
Name = "Console"
AnchorPreset = "WideBottom"
AnchorOffsetTop = 50.0
Children = [ "5" ]

[5]
Prefab = "FullRectWithHierarchy.toml"
Name = "Play Buttons"
AnchorPreset = "TopCenter"
Margin = 10.0