[1]
Component = "Echidna2.Editor, Echidna2"
Named = "01"
RectTransform = "02"
RectLayout = "03"
PrefabChildren = "04"
Viewport = "10"
HierarchyDisplay = "15"
PrefabPath = "Prefabs/Editor.toml"

[01]
Component = "Echidna2.Core.Named, Echidna2.Core"
Name = "Editor"

[02]
Component = "Echidna2.Gui.RectTransform, Echidna2.Gui"
IsGlobal = true
AnchorPreset = "Full"

[03]
Component = "Echidna2.Gui.RectLayout, Echidna2.Gui"
RectTransform = "02"
Hierarchy = "04"

[04]
Component = "Echidna2.Core.Hierarchy, Echidna2.Core"
Children = [ "2" ]

[2]
Prefab = "VLayoutWithHierarchy.toml"
Name = "Toolbar Box"
AnchorPreset = "Full"
Children = [ "3", "5" ]

[3]
Prefab = "RectWithHierarchy.toml"
Name = "Toolbar"
MinimumSize = { X = 0.0, Y = 50.0 }
Children = [ "4" ]

[4]
Prefab = "TextRect.toml"
Name = "Toolbar Text"
TextString = "This is a toolbar."
AnchorPreset = "Full"

[5]
Prefab = "HLayoutWithHierarchy.toml"
Name = "Main Panels"
VerticalExpand = true
Children = [ "6", "9", "12" ]

[6]
Prefab = "VLayoutWithHierarchy.toml"
Name = "Hierarchy Box"
Children = [ "7", "8" ]

[7]
Prefab = "RectWithHierarchy.toml"
Name = "Hierarchy"
VerticalExpand = true
MinimumSize = { X = 200.0, Y = 0.0 }
Children = [ "15" ]

[8]
Prefab = "RectWithHierarchy.toml"
Name = "File Browser"
VerticalExpand = true
MinimumSize = { X = 200.0, Y = 0.0 }

[9]
Prefab = "VLayoutWithHierarchy.toml"
Name = "Scene Box"
HorizontalExpand = true
Children = [ "10", "11" ]

[10]
Prefab = "ViewportGui.toml"
Name = "Scene"
VerticalExpand = true

[11]
Prefab = "RectWithHierarchy.toml"
Name = "Console"
MinimumSize = { X = 100.0, Y = 200.0 }

[12]
Prefab = "VLayoutWithHierarchy.toml"
Name = "Inspector Box"
Children = [ "13" ]

[13]
Prefab = "RectWithHierarchy.toml"
Name = "Inspector"
VerticalExpand = true
MinimumSize = { X = 200.0, Y = 0.0 }
Children = [ "14" ]

[14]
Prefab = "ButtonRect.toml"
Name = "Inspector Button"
AnchorPreset = "Center"
MinimumSize = { X = 150.0, Y = 50.0 }

[15]
Prefab = "HierarchyDisplay.toml"
Name = "Hierarchy Display"
AnchorPreset = "Full"
TopMargin = 10.0