[1]
Component = "Echidna2.Editor, Echidna2"
Named = "01"
RectTransform = "02"
RectLayout = "03"
PrefabChildren = "04"
Viewport = "2"
PrefabPath = "Prefabs/Some3dScene.toml"

[01]
Component = "Echidna2.Core.Named, Echidna2.Core"
Name = "Editor"

[02]
Component = "Echidna2.Gui.RectTransform, Echidna2.Gui"
IsGlobal = true
AnchorPreset = "Full"

[03]
Component = "Echidna2.Gui.RectLayout, Echidna2.Gui"
RectTransform = "02"
Hierarchy = "04"

[04]
Component = "Echidna2.Core.Hierarchy, Echidna2.Core"
Children = [ "2", "3" ]

[2]
Prefab = "EditorViewport3D.toml"
Name = "Scene"
AnchorPreset = "Full"

[3]
Prefab = "RectLayoutWithHierarchy.toml"
Name = "Overlay"
AnchorPreset = "Full"
Children = [ "4", "9", "14" ]

[4]
Prefab = "RectWithHierarchy.toml"
Name = "Console"
AnchorPreset = "WideBottom"
AnchorOffsetTop = 50.0
Children = [ "5-1" ]

[5-1]
Prefab = "RectLayoutWithHierarchy.toml"
Name = "Play Buttons Position Resetter"
AnchorPreset = "TopCenter"
Children = [ "5" ]

[5]
Prefab = "FullRectWithHierarchy.toml"
Name = "Play Buttons"
AnchorPreset = "Center"
Margin = 10.0
Children = [ "6" ]

[6]
Prefab = "HLayoutWithHierarchy.toml"
Name = "Play Buttons Layout"
Spacing = 10.0
Children = [ "7", "8" ]

[7]
Prefab = "RectWithHierarchy.toml"
Name = "Play Button"
MinimumSize = { X = 26.0, Y = 26.0 }
Color = { R = 0.0, G = 1.0, B = 0.0, A = 1.0 }

[8]
Prefab = "RectWithHierarchy.toml"
Name = "Stop Button"
MinimumSize = { X = 26.0, Y = 26.0 }
Color = { R = 1.0, G = 0.0, B = 0.0, A = 1.0 }

[9]
Prefab = "FullRectWithHierarchy.toml"
Name = "Scene Context Buttons"
AnchorPreset = "TopCenter"
AnchorOffsetTop = -10.0
AnchorOffsetBottom = -10.0
Margin = 10.0
Children = [ "10" ]

[10]
Prefab = "HLayoutWithHierarchy.toml"
Name = "Scene Context Buttons Layout"
Spacing = 10.0
Children = [ "11", "12", "13" ]

[11]
Prefab = "RectWithHierarchy.toml"
Name = "3D View Button"
MinimumSize = { X = 26.0, Y = 26.0 }
Color = { R = 1.0, G = 0.0, B = 0.0, A = 1.0 }

[12]
Prefab = "RectWithHierarchy.toml"
Name = "2D View Button"
MinimumSize = { X = 26.0, Y = 26.0 }
Color = { R = 0.0, G = 0.0, B = 1.0, A = 1.0 }

[13]
Prefab = "RectWithHierarchy.toml"
Name = "Gui View Button"
MinimumSize = { X = 26.0, Y = 26.0 }
Color = { R = 0.0, G = 1.0, B = 0.0, A = 1.0 }

[14]
Prefab = "FullRectWithHierarchy.toml"
Name = "Side Panel Buttons"
AnchorPreset = "TopRight"
AnchorOffsetTop = -10.0
AnchorOffsetBottom = -10.0
AnchorOffsetRight = -10.0
AnchorOffsetLeft = -10.0
Margin = 10.0
Children = [ "15" ]

[15]
Prefab = "VLayoutWithHierarchy.toml"
Name = "Side Panel Buttons Layout"
Spacing = 10.0
Children = [ "16", "17", "18", "19" ]

[16]
Prefab = "RectWithHierarchy.toml"
Name = "Object Panel Button"
MinimumSize = { X = 26.0, Y = 26.0 }
Color = { R = 1.0, G = 0.0, B = 0.0, A = 1.0 }

[17]
Prefab = "RectWithHierarchy.toml"
Name = "Component Panel Button"
MinimumSize = { X = 26.0, Y = 26.0 }
Color = { R = 0.0, G = 0.0, B = 1.0, A = 1.0 }

[18]
Prefab = "RectWithHierarchy.toml"
Name = "Material Panel Button"
MinimumSize = { X = 26.0, Y = 26.0 }
Color = { R = 0.0, G = 1.0, B = 0.0, A = 1.0 }

[19]
Prefab = "RectWithHierarchy.toml"
Name = "State Machine Panel Button"
MinimumSize = { X = 26.0, Y = 26.0 }
Color = { R = 1.0, G = 0.0, B = 1.0, A = 1.0 }
