[1]
Component = "Echidna2.Hierarchy, Echidna2"
Named = "2"
RectTransform = "4"
Layout = "5"
DisplayElements = "3"
HierarchyToDisplay = "6"

[2]
Component = "Echidna2.Core.Named, Echidna2.Core"
Name = "Hierarchy Display"

[3]
Component = "Echidna2.Core.Hierarchy, Echidna2.Core"

[4]
Component = "Echidna2.Gui.RectTransform, Echidna2.Gui"

[5]
Component = "Echidna2.Gui.FullLayout, Echidna2.Gui"
RectTransform = "4"
Hierarchy = "3"

[6]
Component = "Echidna2.Core.Hierarchy, Echidna2.Core"