[1]
Component = "Echidna2.HLayoutWithHierarchy, Echidna2"
Named = "2"
RectTransform = "4"
Layout = "5"
PrefabChildren = "3"

[2]
Component = "Echidna2.Core.Named, Echidna2.Core"
Name = "Horizontal Layout"

[3]
Component = "Echidna2.Core.Hierarchy, Echidna2.Core"

[4]
Component = "Echidna2.Gui.RectTransform, Echidna2.Gui"

[5]
Component = "Echidna2.Gui.HorizontalLayout, Echidna2.Gui"
RectTransform = "4"
Hierarchy = "3"