[1]
Component = "Echidna2.TextRect, Echidna2"
Named = "2"
RectTransform = "3"
Text = "4"

[2]
Component = "Echidna2.Core.Named, Echidna2.Core"
Name = "Text"

[3]
Component = "Echidna2.Gui.RectTransform, Echidna2.Gui"

[4]
Component = "Echidna2.Gui.Text, Echidna2.Gui"
RectTransform = "3"