[1]
Component = "Echidna2.ViewportGui, Echidna2"
Named = "2"
RectTransform = "3"
RenderTarget = "5"
Hierarchy = "6"
Camera = "7"
GuiRectLayout = "8"
GuiRectTransform = "9"

[2]
Component = "Echidna2.Core.Named, Echidna2.Core"
Name = "Viewport"

[3]
Component = "Echidna2.Gui.RectTransform, Echidna2.Gui"

[5]
Component = "Echidna2.Rendering.RenderTarget, Echidna2.Rendering"
CameraHaver = "7"

[6]
Component = "Echidna2.Core.Hierarchy, Echidna2.Core"

[7]
Component = "Echidna2.Gui.GuiCamera, Echidna2.Gui"
Size = { X = 800.0, Y = 600.0 }
World = "6"

[8]
Component = "Echidna2.Gui.RectLayout, Echidna2.Gui"
Hierarchy = "6"
RectTransform = "9"

[9]
Component = "Echidna2.Gui.RectTransform, Echidna2.Gui"
LocalSize = { X = 800.0, Y = 600.0 }
IsGlobal = true